### PR TITLE
Fixed Vector::erase() and Vector::~Vector()

### LINKED ISSUE #52: Vector needs fixing
* ``Vector::erase()`` goes out of bounds when ``i`` equals ``size - 1``
* ``Vector::~Vector()`` uses ``Vector::clear()`` which allocates another array

### PR DESCRIPTION
**Pull request by ChrisRzech**
Closes #52 
(got rid of one of the warnings from ``Vector``)
Almost Christmas boys

### CODE REVIEW

File: utils/vector.hpp [hunk 1]
```diff
@@ -350,11 +350,14 @@ const T* Vector<T>::end() const
 template <class T>
 void Vector<T>::erase(uint32_t position)
 {
-    for(uint32_t i = position; i < size; i++)
+    if(size != 0)
     {
-        array[i] = array [i + 1];
+        for(uint32_t i = position; i < size - 1; i++)
```
Comment (dacruz21) [inline utils/vector.hpp]: This is so unnecessary, we can definitely do this in O(1)

Comment (ChrisRzech) [reply utils/vector.hpp]: How are you going to move all the elements in O(1)?
